### ISSUE TITLE
httpx.RemoteProtocolError: Server disconnected without sending a response.

### ISSUE THREAD

**Issue by Natural12349978** [acheong08/EdgeGPT-Proxy#6]
我在render上面部署了这个Proxy脚本
![image](https://user-images.githubusercontent.com/117015081/229442712-d5a7ad27-84d6-436b-a470-bc8f6187f231.png)
当我尝试执行这样的代码`python EdgeGPT.py --style creative --cookie-file "D:/documents/cookie.json" --proxy "https://edge-xiali.onrender.com/edgesvc/turing/conversation/create"`时EdgeGPT产生了报错
EdgeGPT generated an error when I tried to execute such code：
```
Traceback (most recent call last):
  File "D:\Python3.10.5\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\Python3.10.5\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\Python3.10.5\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "D:\Python3.10.5\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "D:\Python3.10.5\lib\site-packages\httpcore\_sync\http_proxy.py", line 261, in handle_request
    connect_response = self._connection.handle_request(
  File "D:\Python3.10.5\lib\site-packages\httpcore\_sync\connection.py", line 90, in handle_request
    return self._connection.handle_request(request)
  File "D:\Python3.10.5\lib\site-packages\httpcore\_sync\http11.py", line 112, in handle_request
    raise exc
  File "D:\Python3.10.5\lib\site-packages\httpcore\_sync\http11.py", line 91, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "D:\Python3.10.5\lib\site-packages\httpcore\_sync\http11.py", line 155, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "D:\Python3.10.5\lib\site-packages\httpcore\_sync\http11.py", line 205, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\downloads\Compressed\EdgeGPT-master\EdgeGPT-master\src\EdgeGPT.py", line 531, in <module>
    asyncio.run(main())
  File "D:\Python3.10.5\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python3.10.5\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\downloads\Compressed\EdgeGPT-master\EdgeGPT-master\src\EdgeGPT.py", line 420, in main
    bot = Chatbot(proxy=args.proxy)
  File "D:\downloads\Compressed\EdgeGPT-master\EdgeGPT-master\src\EdgeGPT.py", line 344, in __init__
    Conversation(self.cookiePath, self.cookies, self.proxy),
  File "D:\downloads\Compressed\EdgeGPT-master\EdgeGPT-master\src\EdgeGPT.py", line 235, in __init__
    response = self.session.get(
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 1045, in get
    return self.request(
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 908, in send
    response = self._send_handling_auth(
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "D:\Python3.10.5\lib\site-packages\httpx\_transports\default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "D:\Python3.10.5\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Python3.10.5\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.
```
然后有时他的报错又是这样（Sometimes there are such problems）：
```
Traceback (most recent call last):
  File "D:\Python3.10.5\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\Python3.10.5\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\Python3.10.5\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "D:\Python3.10.5\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "D:\Python3.10.5\lib\site-packages\httpcore\_sync\http_proxy.py", line 270, in handle_request
    raise ProxyError(msg)
httpcore.ProxyError: 400 Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\downloads\Compressed\EdgeGPT-master\EdgeGPT-master\src\EdgeGPT.py", line 531, in <module>
    asyncio.run(main())
  File "D:\Python3.10.5\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python3.10.5\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\downloads\Compressed\EdgeGPT-master\EdgeGPT-master\src\EdgeGPT.py", line 420, in main
    bot = Chatbot(proxy=args.proxy)
  File "D:\downloads\Compressed\EdgeGPT-master\EdgeGPT-master\src\EdgeGPT.py", line 344, in __init__
    Conversation(self.cookiePath, self.cookies, self.proxy),
  File "D:\downloads\Compressed\EdgeGPT-master\EdgeGPT-master\src\EdgeGPT.py", line 235, in __init__
    response = self.session.get(
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 1045, in get
    return self.request(
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 908, in send
    response = self._send_handling_auth(
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\Python3.10.5\lib\site-packages\httpx\_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "D:\Python3.10.5\lib\site-packages\httpx\_transports\default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "D:\Python3.10.5\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Python3.10.5\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ProxyError: 400 Bad Request
```
我想知道如何解决

**Comment by DreamMaoMao** [comment]
这是你自己搭建的对话域名反向代理？你这个要直接去替换掉代码里对应的链接才可以，--proxy 是指定的http代理不是填入你的具体域名反代

**Comment by DreamMaoMao** [comment]
或者在运行代码前先export BING_PROXY_URL="https://edge-xiali.onrender.com/edgesvc/turing/conversation/create"
![image](https://user-images.githubusercontent.com/30348075/229683799-e2e7fdf6-1860-4272-8657-6c09918cb89b.png)

**Comment by Natural12349978** [comment]
> 或者在运行代码前先export BING_PROXY_URL="https://edge-xiali.onrender.com/edgesvc/turing/conversation/create" ![image](https://user-images.githubusercontent.com/30348075/229683799-e2e7fdf6-1860-4272-8657-6c09918cb89b.png)

首先感谢你的解答。我是在Windows系统下运行的EdgeGPT脚本。所以我按照你的要求替换了py文件内容。我成功了。非常感谢您！
